### PR TITLE
Upgrade libraries and use docker-compose

### PR DESCRIPTION
**Pull request by luisvt**
* Upgrade libraries to be compatible with latest dart sdk
* use docker compose to handle databases installation and testing

### CODE REVIEW

**Comment by ustims** [comment]
Thanks, this looks awesome! Is there any way we can make it work on travis? Some short technical description will also help. Sorry I don't have much time to do that. 

Thanks!

**Comment by luisvt** [comment]
I'm still checking how to make it run with travis, however I have some some docs in the web:

https://docs.travis-ci.com/user/docker/

I'll try to add it and then contact you again

**Comment by luisvt** [comment]
They are passing now, however I'm not sure if the configuration is ok.

**Comment by luisvt** [comment]
I think the current configuration is ok now

**Review by ustims — APPROVED** [review]

**Comment by luisvt** [comment]
please merge this branch also

**Pull request merged**
