### PR TITLE
Refactor tests, use pkg/test

### PR DESCRIPTION
**Pull request by kevmoo**
Ready to review, @ustims !

### CODE REVIEW

**Comment by kevmoo** [comment]
Let me know what you think, @ustims

**Comment by ustims** [comment]
It looks great 👍🏻 Thanks for working on this!
Could you make test filenames more consistent:
```
test/mondo_test.dart
test/mysql_integration_test.dart
test/postgres_test.dart
```
?

**Comment by kevmoo** [comment]
@ustims please take another look

**Comment by ustims** [comment]
It looks really nice except one typo: 
```
mondo_integration_test.dart
   ^
```
Shouldn't it be 'mongo'?

**Comment by kevmoo** [comment]
@ustims Yup. Sorry. Fixed.

**Pull request merged**
