### PR TITLE
tweaks

### PR DESCRIPTION
**Pull request by kevmoo**
[Review on Reviewable](https://reviewable.io/reviews/ustims/dartorm/11)

### CODE REVIEW

**Comment by ustims** [comment]
Hi Kevin! Thanks for this! I've added Travis CI but haven't configured it yet so don't mind it. I will check it in a few hours.

**Comment by kevmoo** [comment]
@ustims Not a problem. Let me know if you need help w/ that. I have a bit of experience w/ travis + Dart

**Comment by ustims** [comment]
Could you pull from master in order to allow travis rebuild this pr?

**Comment by kevmoo** [comment]
@ustims sadly, pull requests don't have access to environment variables – it's a way to leaking secrets

**Comment by ustims** [comment]
@kevmoo I've added that variables into .travis.yml, will it help?

**Comment by kevmoo** [comment]
Looks like we're good!

**Pull request merged**
